"""Add embedding to Business

Revision ID: a8612f15c5f3
Revises: cf7e45be7738
Create Date: 2026-07-19 21:48:44.773160
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector

revision = 'a8612f15c5f3'
down_revision = 'cf7e45be7738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column('businesses', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'embedding')
    # ### end Alembic commands ###

