"""add title to chat sessions

Revision ID: cf7e45be7738
Revises: 0002_chat_sessions
Create Date: 2026-07-01 19:19:08.281994

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'cf7e45be7738'
down_revision = '0002_chat_sessions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_users')
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('chat_sessions', sa.Column('messages', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'messages')
    op.drop_column('chat_sessions', 'title')
    op.create_table('test_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_users_pkey'),
    sa.UniqueConstraint('email', name='test_users_email_key'),
    sa.UniqueConstraint('username', name='test_users_username_key')
    )
    # ### end Alembic commands ###

